version: '5'

services:
  mongodb_container:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
